### ISSUE TITLE
> @mwm0522

### ISSUE THREAD

**Issue by 2egg** [zhwangart/gitalk#22]
> @mwm0522
> 我想请教下，你首页的内容默认收起来，点击标题阅读全文是怎么做的，我的怎么是把全部文章展示出来了。我也是搞了一下午，后来我看看你的请求链接，才发现我的请求链接错误了

#### 我是这么做的，不知道能不能帮到你：
1、模板文件中（还是以 ejs 为例）写：
``` ejs
<% if (post.excerpt && index){ %>
  <%- post.excerpt %>
    <% if (theme.excerpt_link){ %>
      <a class="article-more-link" href="<%- url_for(post.path) %>"><%= theme.excerpt_link %></a>
    <% } %>
  <% } else { %>
    <%- post.content %>
<% } %>
```
2、Theme `config.yml` 中定义 `excerpt_link` 文本内容
``` yml
excerpt_link: Read More...
```
3、Markdown 文档：
``` markdown
摘要...
<!--more-->
正文...
```
然后首页就只显示 摘要... 了！

_Originally posted by @zhwangart in https://github.com/zhwangart/gitalk/issues/6#issuecomment-449741554_

**Comment by 2egg** [comment]
请教一下，初次使用！ 您说的模板.ejs文件是指哪个！我在您的主题中Layout 中找到许多.ejs 文件

**Comment by zhwangart** [comment]
> @2egg `layout/_partial/article.ejs`
