### ISSUE TITLE
Gitalk | 数学家

### ISSUE THREAD

**Issue by zhwangart** [zhwangart/gitalk#3]
https://zhwangart.github.io/2018/12/06/Gitalk/ 

 数学家的博客

**Comment by King003** [comment]
你好作者，我很喜欢你的主题，请教一下你的鲨鱼SVG是哪里找的？我挺喜欢这个标志的，，还有相册跟文章里涉及到的图片 能详细点告诉我是怎么弄的吗，具体在哪个目录弄，还有关于那里，，详细步骤能告诉我吗？非常感谢

**Comment by King003** [comment]
还有是在哪个文件里引入Gitalk，还是自己要在哪个目录下新创建一个？

**Comment by zhwangart** [comment]
> @King003
> 还有是在哪个文件里引入Gitalk，还是自己要在哪个目录下新创建一个？

先谢谢你认可 Ocean 的设计！小鲨鱼 svg 标志是我自己画的，相册与关于需要新建一个 page 的，比如新建关于：
``` xml
$ hexo new page about
```
另外我会在把 Ocean 的说明文档再写详细一些，然后 Gitalk 我也会更新上去，并且附上详细的说明文档。如果你正在使用 Ocean 的话，那么看到我更新 Gitalk 后 `git pull` 一下就好。

**Comment by King003** [comment]
好的，非常感谢，我是个新手
