### ISSUE TITLE
albums添加了但是不生效

### ISSUE THREAD

**Issue by conan51551** [zhwangart/gitalk#73]

**Comment by conan51551** [comment]
---
title: Gallery
date: 2021-12-03 18:23:29
albums: [
        ["https://z3.ax1x.com/2021/11/27/oeWnHO.md.jpg","描述"],
        ]
---
头部是这么写的

**Comment by conan51551** [comment]
albums:
[
["点击放大后的url", "图片展示的url", "图片描述"],
]
已经可以了，解决方法是发现这个有三个参数

**Comment by real-jiakai** [comment]
感谢你

**Comment by real-jiakai** [comment]
![image](https://user-images.githubusercontent.com/82650452/164838749-30de16e3-a921-4937-ba64-006dbfd1429a.png)
这个教程应该更新一下

**Comment by zhwangart** [comment]
> ![image](https://user-images.githubusercontent.com/82650452/164838749-30de16e3-a921-4937-ba64-006dbfd1429a.png) 这个教程应该更新一下

感谢提醒，已经更新。
